name: Build and Push Docker Image

on:
  push:
    branches:
      - 'test*'

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: get-name
        run: |
            echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
            echo "REPO_OWNER=$(echo ${{ github.repository_owner}} | tr '[:upper:]' '[:lower:]' )" >> $GITHUB_ENV
      - name: print-name
        run: |
            echo "${{ env.REPO_NAME }}"
            echo "${{ env.REPO_OWNER }}"

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:${{ github.sha }} .
